// Code generated by mockery v2.42.2. DO NOT EDIT.

package apiclient

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type MockClientWithResponsesInterface struct {
	mock.Mock
}

type MockClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterface_Expecter {
	return &MockClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// CreateClusterWithBodyWithResponse provides a mock function with given fields: ctx, contentType, body, reqEditors
func (_m *MockClientWithResponsesInterface) CreateClusterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterWithBodyWithResponse")
	}

	var r0 *CreateClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...RequestEditorFn) (*CreateClusterResponse, error)); ok {
		return rf(ctx, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, ...RequestEditorFn) *CreateClusterResponse); ok {
		r0 = rf(ctx, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClusterWithBodyWithResponse'
type MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call struct {
	*mock.Call
}

// CreateClusterWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - contentType string
//   - body io.Reader
//   - reqEditors ...RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) CreateClusterWithBodyWithResponse(ctx interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call {
	return &MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call{Call: _e.mock.On("CreateClusterWithBodyWithResponse",
		append([]interface{}{ctx, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call) Run(run func(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn)) *MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call) Return(_a0 *CreateClusterResponse, _a1 error) *MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call) RunAndReturn(run func(context.Context, string, io.Reader, ...RequestEditorFn) (*CreateClusterResponse, error)) *MockClientWithResponsesInterface_CreateClusterWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// CreateClusterWithResponse provides a mock function with given fields: ctx, body, reqEditors
func (_m *MockClientWithResponsesInterface) CreateClusterWithResponse(ctx context.Context, body CreateCluster, reqEditors ...RequestEditorFn) (*CreateClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterWithResponse")
	}

	var r0 *CreateClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, CreateCluster, ...RequestEditorFn) (*CreateClusterResponse, error)); ok {
		return rf(ctx, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, CreateCluster, ...RequestEditorFn) *CreateClusterResponse); ok {
		r0 = rf(ctx, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, CreateCluster, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_CreateClusterWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClusterWithResponse'
type MockClientWithResponsesInterface_CreateClusterWithResponse_Call struct {
	*mock.Call
}

// CreateClusterWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - body CreateCluster
//   - reqEditors ...RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) CreateClusterWithResponse(ctx interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_CreateClusterWithResponse_Call {
	return &MockClientWithResponsesInterface_CreateClusterWithResponse_Call{Call: _e.mock.On("CreateClusterWithResponse",
		append([]interface{}{ctx, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_CreateClusterWithResponse_Call) Run(run func(ctx context.Context, body CreateCluster, reqEditors ...RequestEditorFn)) *MockClientWithResponsesInterface_CreateClusterWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(CreateCluster), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_CreateClusterWithResponse_Call) Return(_a0 *CreateClusterResponse, _a1 error) *MockClientWithResponsesInterface_CreateClusterWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_CreateClusterWithResponse_Call) RunAndReturn(run func(context.Context, CreateCluster, ...RequestEditorFn) (*CreateClusterResponse, error)) *MockClientWithResponsesInterface_CreateClusterWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClusterWithResponse provides a mock function with given fields: ctx, clusterId, reqEditors
func (_m *MockClientWithResponsesInterface) DeleteClusterWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*DeleteClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClusterWithResponse")
	}

	var r0 *DeleteClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) (*DeleteClusterResponse, error)); ok {
		return rf(ctx, clusterId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) *DeleteClusterResponse); ok {
		r0 = rf(ctx, clusterId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DeleteClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_DeleteClusterWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClusterWithResponse'
type MockClientWithResponsesInterface_DeleteClusterWithResponse_Call struct {
	*mock.Call
}

// DeleteClusterWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - reqEditors ...RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) DeleteClusterWithResponse(ctx interface{}, clusterId interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_DeleteClusterWithResponse_Call {
	return &MockClientWithResponsesInterface_DeleteClusterWithResponse_Call{Call: _e.mock.On("DeleteClusterWithResponse",
		append([]interface{}{ctx, clusterId}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_DeleteClusterWithResponse_Call) Run(run func(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn)) *MockClientWithResponsesInterface_DeleteClusterWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_DeleteClusterWithResponse_Call) Return(_a0 *DeleteClusterResponse, _a1 error) *MockClientWithResponsesInterface_DeleteClusterWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_DeleteClusterWithResponse_Call) RunAndReturn(run func(context.Context, string, ...RequestEditorFn) (*DeleteClusterResponse, error)) *MockClientWithResponsesInterface_DeleteClusterWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterWithResponse provides a mock function with given fields: ctx, clusterId, reqEditors
func (_m *MockClientWithResponsesInterface) GetClusterWithResponse(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn) (*GetClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterWithResponse")
	}

	var r0 *GetClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) (*GetClusterResponse, error)); ok {
		return rf(ctx, clusterId, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...RequestEditorFn) *GetClusterResponse); ok {
		r0 = rf(ctx, clusterId, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_GetClusterWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterWithResponse'
type MockClientWithResponsesInterface_GetClusterWithResponse_Call struct {
	*mock.Call
}

// GetClusterWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - reqEditors ...RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) GetClusterWithResponse(ctx interface{}, clusterId interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_GetClusterWithResponse_Call {
	return &MockClientWithResponsesInterface_GetClusterWithResponse_Call{Call: _e.mock.On("GetClusterWithResponse",
		append([]interface{}{ctx, clusterId}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_GetClusterWithResponse_Call) Run(run func(ctx context.Context, clusterId string, reqEditors ...RequestEditorFn)) *MockClientWithResponsesInterface_GetClusterWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]RequestEditorFn, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_GetClusterWithResponse_Call) Return(_a0 *GetClusterResponse, _a1 error) *MockClientWithResponsesInterface_GetClusterWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_GetClusterWithResponse_Call) RunAndReturn(run func(context.Context, string, ...RequestEditorFn) (*GetClusterResponse, error)) *MockClientWithResponsesInterface_GetClusterWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// ListClustersWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *MockClientWithResponsesInterface) ListClustersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListClustersResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListClustersWithResponse")
	}

	var r0 *ListClustersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) (*ListClustersResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...RequestEditorFn) *ListClustersResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ListClustersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_ListClustersWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClustersWithResponse'
type MockClientWithResponsesInterface_ListClustersWithResponse_Call struct {
	*mock.Call
}

// ListClustersWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) ListClustersWithResponse(ctx interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_ListClustersWithResponse_Call {
	return &MockClientWithResponsesInterface_ListClustersWithResponse_Call{Call: _e.mock.On("ListClustersWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_ListClustersWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...RequestEditorFn)) *MockClientWithResponsesInterface_ListClustersWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_ListClustersWithResponse_Call) Return(_a0 *ListClustersResponse, _a1 error) *MockClientWithResponsesInterface_ListClustersWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_ListClustersWithResponse_Call) RunAndReturn(run func(context.Context, ...RequestEditorFn) (*ListClustersResponse, error)) *MockClientWithResponsesInterface_ListClustersWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClusterWithBodyWithResponse provides a mock function with given fields: ctx, clusterId, contentType, body, reqEditors
func (_m *MockClientWithResponsesInterface) UpdateClusterWithBodyWithResponse(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId, contentType, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClusterWithBodyWithResponse")
	}

	var r0 *UpdateClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...RequestEditorFn) (*UpdateClusterResponse, error)); ok {
		return rf(ctx, clusterId, contentType, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, ...RequestEditorFn) *UpdateClusterResponse); ok {
		r0 = rf(ctx, clusterId, contentType, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UpdateClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, contentType, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClusterWithBodyWithResponse'
type MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call struct {
	*mock.Call
}

// UpdateClusterWithBodyWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - contentType string
//   - body io.Reader
//   - reqEditors ...RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) UpdateClusterWithBodyWithResponse(ctx interface{}, clusterId interface{}, contentType interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call {
	return &MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call{Call: _e.mock.On("UpdateClusterWithBodyWithResponse",
		append([]interface{}{ctx, clusterId, contentType, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call) Run(run func(ctx context.Context, clusterId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn)) *MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]RequestEditorFn, len(args)-4)
		for i, a := range args[4:] {
			if a != nil {
				variadicArgs[i] = a.(RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(io.Reader), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call) Return(_a0 *UpdateClusterResponse, _a1 error) *MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call) RunAndReturn(run func(context.Context, string, string, io.Reader, ...RequestEditorFn) (*UpdateClusterResponse, error)) *MockClientWithResponsesInterface_UpdateClusterWithBodyWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClusterWithResponse provides a mock function with given fields: ctx, clusterId, body, reqEditors
func (_m *MockClientWithResponsesInterface) UpdateClusterWithResponse(ctx context.Context, clusterId string, body UpdateCluster, reqEditors ...RequestEditorFn) (*UpdateClusterResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, clusterId, body)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClusterWithResponse")
	}

	var r0 *UpdateClusterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, UpdateCluster, ...RequestEditorFn) (*UpdateClusterResponse, error)); ok {
		return rf(ctx, clusterId, body, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, UpdateCluster, ...RequestEditorFn) *UpdateClusterResponse); ok {
		r0 = rf(ctx, clusterId, body, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UpdateClusterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, UpdateCluster, ...RequestEditorFn) error); ok {
		r1 = rf(ctx, clusterId, body, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientWithResponsesInterface_UpdateClusterWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClusterWithResponse'
type MockClientWithResponsesInterface_UpdateClusterWithResponse_Call struct {
	*mock.Call
}

// UpdateClusterWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterId string
//   - body UpdateCluster
//   - reqEditors ...RequestEditorFn
func (_e *MockClientWithResponsesInterface_Expecter) UpdateClusterWithResponse(ctx interface{}, clusterId interface{}, body interface{}, reqEditors ...interface{}) *MockClientWithResponsesInterface_UpdateClusterWithResponse_Call {
	return &MockClientWithResponsesInterface_UpdateClusterWithResponse_Call{Call: _e.mock.On("UpdateClusterWithResponse",
		append([]interface{}{ctx, clusterId, body}, reqEditors...)...)}
}

func (_c *MockClientWithResponsesInterface_UpdateClusterWithResponse_Call) Run(run func(ctx context.Context, clusterId string, body UpdateCluster, reqEditors ...RequestEditorFn)) *MockClientWithResponsesInterface_UpdateClusterWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]RequestEditorFn, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(RequestEditorFn)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(UpdateCluster), variadicArgs...)
	})
	return _c
}

func (_c *MockClientWithResponsesInterface_UpdateClusterWithResponse_Call) Return(_a0 *UpdateClusterResponse, _a1 error) *MockClientWithResponsesInterface_UpdateClusterWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientWithResponsesInterface_UpdateClusterWithResponse_Call) RunAndReturn(run func(context.Context, string, UpdateCluster, ...RequestEditorFn) (*UpdateClusterResponse, error)) *MockClientWithResponsesInterface_UpdateClusterWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientWithResponsesInterface creates a new instance of MockClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
